[package]
name = "mdbx-derive-traits"
version = "0.1.0"
edition = "2024"

[features]
default = ["alloy"]
alloy = ["alloy-primitives"]

[dependencies]
alloy-primitives = {version = "0.8", optional = true}
thiserror.workspace = true
serde_json.workspace = true
zstd.workspace = true
bincode.workspace = true