[package]
name = "mdbx-derive-macros"
version.workspace = true
edition.workspace = true

[dependencies]
syn.workspace = true
quote.workspace = true
itertools.workspace = true
proc-macro2.workspace = true
mdbx-derive-traits.workspace = true

[lib]
proc-macro = true